### ISSUE TITLE
对支持库openssl要求为 1.0版本 debain9 最低安装版本为1.1 

### ISSUE THREAD

**Issue by xs-sjw** [aliyun/ossfs#107]
使用命令
ossfs xscloud /root/ossfs -ourl=http://oss-cn-shenzhen-internal.aliyuncs.com
提示
ossfs: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

原因是 ossfs 必须使用 openssl1.0 版本
而debain9 最低安装openssl1.1 的版本

请问这种问题应该如何解决

**Comment by Low-power** [comment]
``apt install libssl1.0.2``

**Comment by imsjw** [comment]
已经通过源码安装的方式解决了

**Comment by wushilin** [comment]
# apt install libssl1.0.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libssl1.0.2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libssl1.0.2' has no installation candidate

**Comment by Low-power** [comment]
wushilin, either you didn't use a Debian 9 (stretch) system, or you has configured `/etc/apt/sources.list` incorrectly.

**Comment by wushilin** [comment]
Well I used default alicloud Debian 9 how can you say I configured
incorrectly?

Anyway, I compiled from source myself.

**Comment by Low-power** [comment]
Package `libssl1.0.2` does exists for Debian 9, you can find it at https://packages.debian.org/search?keywords=libssl1.0.2&searchon=names&suite=stretch&section=main or https://packages.debian.org/stretch/libssl1.0.2

So I guess may be the default configuration in that VM template is incorrect, or the default configured mirror site is not functioning; you can try to configure (by editing `/etc/apt/sources.list`) another mirror site instead, for example using 163's mirror:
```
deb http://mirrors.163.com/debian/ stretch main contrib
deb http://mirrors.163.com/debian/ stretch-updates main contrib
```
And don't forget to run `apt update` after editing this file.

**Comment by xs-sjw** [comment]
多谢
