### ISSUE TITLE
Generate Ubuntu 18.04 LTS package.

### ISSUE THREAD

**Issue by zolan** [aliyun/ossfs#115]
I am using Ubuntu 18.04 LTS and I'm installing the ossfs_1.80.5_ubuntu16.04_amd64.deb
 package.

The problem is, when installing this package in Ubuntu 18.04 LTS, the dependencies are not compatible with the default npm package.

I need both npm and ossfs installed at the same time and currently I can not do so as when I install one of them it uninstalls the other one.

Since 18.04 is an LTS release, it seems like it would be a good idea to have one available anyway.

Thank you for your consideration.

**Comment by ermazi** [comment]
+1, 19.04 should use libssl1.1

**Comment by huiguangjun** [comment]
http://gosspublic.alicdn.com/ossfs/ossfs_1.80.6_ubuntu18.04_amd64.deb?spm=a2c4g.11186623.2.11.7cde7358vkIvw4&file=ossfs_1.80.6_ubuntu18.04_amd64.deb
