### ISSUE TITLE
Q: 如何开机自动挂载ossfs？能改默认的 /etc/passwd-ossfs 文档地点吗？

### ISSUE THREAD

**Issue by ldkhang** [aliyun/ossfs#15]
针对FAQ里面的问题：如何开机自动挂载ossfs？

Step 1 有提到默认的密码文档地址设置为 /etc/passwd-ossfs。请问能变改吗？Step 2下面的对应命令是如何呢？

谢谢

**Comment by hryang** [comment]
您可以把文件放在/your_path/passwd-ossfs下，然后在通过ossfs挂载时增加
-opasswd_file=/your_path/passwd-ossfs
参数来指定。

step2中的命令
ossfs#your_bucket_name your_mount_point fuse _netdev,url=your_url,allow_other,passwd_file=xxx 0 0

另外，您的passwd file需要设置合适的权限。
