### ISSUE TITLE
watch文件

### ISSUE THREAD

**Issue by zhengnz** [aliyun/ossfs#25]
请问使用ossfs，是否可以watch里面的文件或目录，我在阿里的容器服务中使用，挂载到oss，发现无法watch到挂载的文件改变，在ecs里本地目录的文件改变是可以watch到的

**Comment by rockuw** [comment]
能具体说一下你是怎么watch的吗？

**Comment by zhengnz** [comment]
我是利用pm2的watch功能，pm2的watch是用到nodejs的插件chokidar，另外请问利用linux的inotify能监控到挂载的ossfs文件吗？

**Comment by rockuw** [comment]
我先试试pm2，我用过auditd是可以监控到挂载目录的访问的

**Comment by rockuw** [comment]
![image](https://cloud.githubusercontent.com/assets/1209779/14667310/37f10cc0-0711-11e6-8a0a-22b6b74e3004.png)

我试了一下，可以watch到啊。我的挂载命令：

**Comment by zhengnz** [comment]
你好，我在自己的ecs挂载ossfs，也在容器服务挂载ossfs，我发现自己的ecs对touch有反应，应用会重启，但是容器服务里对touch没反应，这是我的process.json
`{
  "apps": [{
    "script": "app.js",
    "name": "factory",
    "max_memory_restart": "700M",
    "instance": 1,
    "watch": ["/watch/version.txt"]
  }]
}`

**Comment by zhengnz** [comment]
是不是监控对本机的touch才有效，不会让其他服务器对这个文件的touch产生反应？

**Comment by rockuw** [comment]
@zhengnz 你是说你在两个地方挂载了ossfs，然后在其中一个地方touch，期望在另外一个地方被watch到？

这当然是不可能的。。对ossfs的访问只会同步到OSS，不会同步到其他的ossfs。

**Comment by zhengnz** [comment]
好的，是我误解了，谢谢您的耐心解答
