### ISSUE TITLE
权限依然有问题

### ISSUE THREAD

**Issue by bestony** [aliyun/ossfs#3]
为啥不改成我PR的版本= =。
用wget来处理
![6.png](https://ooo.0o0.ooo/2015/12/18/5673f292cb193.png)
用SSH依然有问题的。。。。
不想PR直接修改也行啊= =

**Comment by hryang** [comment]
您好，请换用https的地址clone。

**Comment by hryang** [comment]
我先关闭issue，如果有问题您再提。
