### ISSUE TITLE
神奇目录

### ISSUE THREAD

**Issue by fu7iang** [aliyun/ossfs#49]
环境:
CentOS 7 x64
ossfs 1.8.0
将 bucket01 挂载到本地 ~/bk01

重现步骤:
1. ~/bk01 下新建目录 dirA;
2. 远程通过 OSS-API 删除 dirA;
3. ls -lsa ~/bk01 已经看不到 dirA 目录;
4. 问题：cd ~/bk01/dirA 依然有效，perl -d 检查 ~/bk01/dirA 目录也依然存在；

**Comment by fu7iang** [comment]
卸载、再重新挂载后，目录才彻底消失

**Comment by fu7iang** [comment]
dirA 变成了一个隐藏的、无法用 ls 看到，但是可以用 cd 进入的一个神奇目录

**Comment by fu7iang** [comment]
dirA 的属性、所有者信息正常

**Comment by rockuw** [comment]
https://github.com/aliyun/ossfs/wiki/FAQ#20

ossfs默认会有文件meta的缓存，你可以关闭它。
