### ISSUE TITLE
如何实现0770挂载权限

### ISSUE THREAD

**Issue by ilovintit** [aliyun/ossfs#5]
我使用owncloud搭建私有云盘，把data目录指向ossfs的目录，如果使用allow_other，会变成777权限，owncloud会报错，不允许权限。如果不使用allow_other，但是把用户ID改为apacheID，就会变成700权限，就会导致无法访问的问题。

**Comment by hryang** [comment]
您好，owncloud的用户id是什么？也是apacheID吗？

**Comment by ilovintit** [comment]
我通过查看源码，解决了这个问题，最终挂载的语句是
`ossfs#your_bucket your_mount_point fuse _netdev,url=your_endpoint,uid=your_apache_user_id,gid=your_apache_group_id,umask=007,allow_other 0 0`

**Comment by hryang** [comment]
哦，是的，可以通过umask来设置合适的权限

**Comment by jeromety** [comment]
设置umask后，全部文件和文件夹都使用了统一权限。基于文件夹755文件644原则，我再设置chmod 644 。。。。.jpg后此文件权限并没改变，这是为何呢？

**Comment by liuyuhong66** [comment]
加上-o umask=xxx ，如（ -o umask=027，权限就变成777-027=750（rwxr-x---））

**Comment by crabdave** [comment]
使用OwnCloud Docker容器+阿里云OSS搭建自己的云盘服务 on Centos 7
http://crabdave.iteye.com/blog/2356624

**Comment by 997862** [comment]
我使用ossfs my_bucket /mnt/disk -ourl=oss-cn-beijing.aliyuncs.com -o allow_other -o mp_umask=027挂载目录，挂载不成功！求解！

**Comment by oldthreefeng** [comment]
-ouid=995 -ogid=995 -o mp_umask=007 -o allow_other    挂载加上uid和gid就好了
