### ISSUE TITLE
ossfs 挂载无法完成

### ISSUE THREAD

**Issue by git9527** [aliyun/ossfs#51]
尝试挂载oss的时候一直无法完成，以下是全部的日志
![image](https://cloud.githubusercontent.com/assets/4514520/23214031/38bbaa8c-f948-11e6-9e7f-3ec429c63106.png)
系统CentOS 7.2x64，版本信息如下
![image](https://cloud.githubusercontent.com/assets/4514520/23214156/9feaabf4-f948-11e6-9c79-b8f90b8b1670.png)

**Comment by git9527** [comment]
CentOS 7.2x64

**Comment by rockuw** [comment]
`-f -d`会让ossfs在前台运行，已经挂载成功。
