### ISSUE TITLE
ossfs对应的docker volume plugin如何下载安装

### ISSUE THREAD

**Issue by denglixing** [aliyun/ossfs#55]
如题，我希望在其他机器连接oss作为docker的数据卷，在ECS云服务器中，已经安装了插件，这个插件对外提供吗？
![image](https://cloud.githubusercontent.com/assets/3446841/23978736/97527078-0a30-11e7-87e6-bf444414d4ce.png)

![image](https://cloud.githubusercontent.com/assets/3446841/23978846/1fb82a0c-0a31-11e7-9fed-e375d90b201d.png)

**Comment by xuensheng** [comment]
这个不清楚，请联系ECS售后咨询

**Comment by vimagick** [comment]
👎 Working behind closed doors is what I can see from Aliyun.
闭门造车，令人失望！
