### ISSUE TITLE
上传性能

### ISSUE THREAD

**Issue by liuyuhong66** [aliyun/ossfs#56]
一直听说ossfs高并发读写性能比较差，有没有具体数据，到底多差？有没有相关的测试工具，vdbench可以吗？

**Comment by xuensheng** [comment]
机器：ECS  4核，16GB ，IO优化实例，系统盘为大小40G的高效云盘   
挂载参数： ossfs bucketname /tmp/mnt -ourl=oss-cn-hangzhou-internal.aliyuncs.com -odirect_io -omax_write=131072
测试方法：5路并发持续上传10M文件
结论：上传性能平均40MB/s左右
