### ISSUE TITLE
ossfs权限问题

### ISSUE THREAD

**Issue by jianboy** [aliyun/ossfs#59]
ossfs只能用root启动，切换其他账户（www）启动，出现错误：
`ossfs: could not determine how to establish security credentials.`

而root启动后，无法赋予www权限，
`chown: changing ownership of ‘/ossfs/’: Input/output error`
www用户无法进入ossfs目录！请问怎么操作呢？

**Comment by rockuw** [comment]
https://github.com/aliyun/ossfs/wiki/FAQ#12

**Comment by jianboy** [comment]
不行！在root下看到文件夹权限确实变了。但是到了当前用户，权限却变了。也进不去目录！！

**Comment by jianboy** [comment]
有人么？
用其他用户挂载，权限都是问号。请问怎么做呢？

**Comment by firzen** [comment]
增加一个参数 -oallow_other

**Comment by dannyge** [comment]
@jianboy 看一下阿里云上用户的权限是不是不够

**Comment by 0xJacky** [comment]
我也遇到了这个问题，ownCloud 无法读取或写入
ossfs 1.80.0
ECS, Centos 7.3
