### ISSUE TITLE
ossfs挂载后显示文件访问日期为1970-01-01

### ISSUE THREAD

**Issue by catspoker** [aliyun/ossfs#66]
ossfs挂载到linux主机后，用stat命令查看里面的文件，显示的access和Change时间不正确。
  Size: 188149          Blocks: 368        IO Block: 4096   regular file
Device: 24h/36d Inode: 13          Links: 1
Access: (0666/-rw-rw-rw-)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 1970-01-01 08:00:00.000000000 +0800
Modify: 2017-06-21 10:30:58.000000000 +0800
Change: 1970-01-01 08:00:00.000000000 +0800

**Comment by rockuw** [comment]
你好，这是ossfs的特性，access和change的时间是不会更新的。
