### ISSUE TITLE
OSS挂载后可以创建FTP指向OSS内部某个目录么？

### ISSUE THREAD

**Issue by xiaoyuxiaoyu** [aliyun/ossfs#68]
将OSS挂载到本地目录如：osspath 现在我可以创建一个FTP的根目录指向osspath,通过FTP可以访问到挂载的OSS，并且可以上传等。但是我创建另外一个账户指向OSS内部的某个目录，FTP账户就无法登陆？

**Comment by xuensheng** [comment]
应该是你创建的账户没权限访问oss， 请参考： https://github.com/aliyun/ossfs/wiki/FAQ#11  https://github.com/aliyun/ossfs/wiki/FAQ#12
