### ISSUE TITLE
安装时提示这个是什么问题？

### ISSUE THREAD

**Issue by regboy** [aliyun/ossfs#8]
我的系统是centos 6.5 64位
----------------------------
Total size: 5.7 M
Installed size: 5.7 M
Is this ok [y/N]: y
Downloading Packages:
Running rpm_check_debug
Running Transaction Test

Transaction Check Error:
  file /usr/include/fuse.h from install of ossfs-1.7.9.2-1.x86_64 conflicts with file from package fuse-devel-2.8.3-4.el6.x86_64
  file /usr/include/fuse/fuse.h from install of ossfs-1.7.9.2-1.x86_64 conflicts with file from package fuse-devel-2.8.3-4.el6.x86_64
  file /usr/include/fuse/cuse_lowlevel.h from install of ossfs-1.7.9.2-1.x86_64 conflicts with file from package fuse-devel-2.8.3-4.el6.x86_64
  file /usr/include/fuse/fuse_common.h from install of ossfs-1.7.9.2-1.x86_64 conflicts with file from package fuse-devel-2.8.3-4.el6.x86_64
  file /usr/include/fuse/fuse_common_compat.h from install of ossfs-1.7.9.2-1.x86_64 conflicts with file from package fuse-devel-2.8.3-4.el6.x86_64
  file /usr/include/fuse/fuse_compat.h from install of ossfs-1.7.9.2-1.x86_64 conflicts with file from package fuse-devel-2.8.3-4.el6.x86_64
  file /usr/include/fuse/fuse_lowlevel.h from install of ossfs-1.7.9.2-1.x86_64 conflicts with file from package fuse-devel-2.8.3-4.el6.x86_64
  file /usr/include/fuse/fuse_lowlevel_compat.h from install of ossfs-1.7.9.2-1.x86_64 conflicts with file from package fuse-devel-2.8.3-4.el6.x86_64
  file /usr/include/fuse/fuse_opt.h from install of ossfs-1.7.9.2-1.x86_64 conflicts with file from package fuse-devel-2.8.3-4.el6.x86_64
  file /usr/include/ulockmgr.h from install of ossfs-1.7.9.2-1.x86_64 conflicts with file from package fuse-devel-2.8.3-4.el6.x86_64
  file /sbin/mount.fuse from install of ossfs-1.7.9.2-1.x86_64 conflicts with file from package fuse-2.8.3-4.el6.x86_64
  file /usr/bin/fusermount from install of ossfs-1.7.9.2-1.x86_64 conflicts with file from package fuse-2.8.3-4.el6.x86_64
  file /usr/bin/ulockmgr_server from install of ossfs-1.7.9.2-1.x86_64 conflicts with file from package fuse-2.8.3-4.el6.x86_64

Error Summary

**Comment by hryang** [comment]
您好，错误信息是指您的系统中已经装了fuse 2.8.3版本，而ossfs要求fuse 2.8.4版本。请先卸载fuse-devel再重新安装。
