### ISSUE TITLE
使用ossfs挂载时出现fuse: device not found, try 'modprobe fuse' first

### ISSUE THREAD

**Issue by iteratorlee** [aliyun/ossfs#91]
使用ossfs挂载时，出现：
`fuse: device not found, try 'modprobe fuse' first`
运行 `modprobe fuse`, 出现：
```
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.10.0-28-generic/modules.dep.bin'
modprobe: FATAL: Module fuse not found in directory /lib/modules/4.10.0-28-generic
```

**Comment by panhaoyu** [comment]
Hey, so how did you solved the problem? I met the same one again in the docker container.

**Comment by iteratorlee** [comment]
@panhaoyu Ohh...it'a a long time ago. I just remember that I mounted the `/dev/fuse` device in the host machine to the container and everything goes well after that. You can try that.

**Comment by panhaoyu** [comment]
Sincerely thanks for your help.
ok i tried your method, but still doesn't work.
I solve it in a rude way...
```
docker run --privileged --cap-add=ALL ossfs xxxx
```
just for reference, and if someone else find a better way, please tell me

**Comment by hiobama** [comment]
调皮

**Comment by kk17** [comment]
`--cap-add SYS_ADMIN --device /dev/fuse --security-opt apparmor=unconfined` is the better way.

I also build an ossfs docker image and use it in docker-compose [here](https://github.com/kk17/docker-ossfs/blob/master/docker-compose.yml).

**Comment by Revo-Future** [comment]
在WSL里遇到同样的问题，有解决办法没？
